name: ffmpeg_generator_dart
description: A FFmpeg command-line generator.

# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.14.4
